run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck

linters-settings:
  govet:
    check-shadowing: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
